import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  coverSection: {
    paddingTop: getFigmaDimension(20),
    paddingBottom: getFigmaDimension(40),
    paddingHorizontal: getFigmaDimension(24),
    borderBottomLeftRadius: getFigmaDimension(30),
    borderBottomRightRadius: getFigmaDimension(30),
  },
  headerActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: getFigmaDimension(12),
    marginBottom: getFigmaDimension(20),
  },
  iconButton: {
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImageContainer: {
    alignSelf: 'center',
    marginBottom: getFigmaDimension(16),
    position: 'relative',
  },
  profileImage: {
    width: getFigmaDimension(120),
    height: getFigmaDimension(120),
    borderRadius: getFigmaDimension(60),
    borderWidth: 4,
    borderColor: COLORS.white,
    backgroundColor: COLORS.gray200,
  },
  verifiedBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: getFigmaDimension(36),
    height: getFigmaDimension(36),
    borderRadius: getFigmaDimension(18),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileName: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(26),
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: getFigmaDimension(4),
  },
  profileSkill: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(16),
    color: COLORS.white,
    opacity: 0.9,
    textAlign: 'center',
    marginBottom: getFigmaDimension(24),
  },
  profileStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: getFigmaDimension(16),
    paddingVertical: getFigmaDimension(16),
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(20),
    color: COLORS.white,
    marginTop: getFigmaDimension(6),
    marginBottom: getFigmaDimension(2),
  },
  statLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(12),
    color: COLORS.white,
    opacity: 0.8,
  },
  statDivider: {
    width: 1,
    height: getFigmaDimension(40),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  editButtonContainer: {
    alignItems: 'center',
    marginTop: getFigmaDimension(-20),
    marginBottom: getFigmaDimension(20),
  },
  editProfileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(12),
    borderRadius: getFigmaDimension(25),
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  editProfileText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.white,
    marginLeft: getFigmaDimension(8),
  },
  infoCardsContainer: {
    paddingHorizontal: getFigmaDimension(20),
    marginBottom: getFigmaDimension(24),
    gap: getFigmaDimension(12),
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
  },
  infoCardText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(12),
  },
  section: {
    paddingHorizontal: getFigmaDimension(20),
    marginBottom: getFigmaDimension(24),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(16),
  },
  seeAllText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
  },
  metricsCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
  },
  metricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  metricLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metricLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(12),
  },
  metricValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
  },
  videosScroll: {
    paddingRight: getFigmaDimension(20),
  },
  videoCard: {
    width: getFigmaDimension(160),
    height: getFigmaDimension(200),
    borderRadius: getFigmaDimension(12),
    marginRight: getFigmaDimension(12),
    overflow: 'hidden',
    backgroundColor: COLORS.gray200,
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
  },
  videoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoInfo: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: getFigmaDimension(12),
  },
  videoTitle: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(13),
    color: COLORS.white,
    marginBottom: getFigmaDimension(4),
  },
  videoMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  videoViews: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(11),
    color: COLORS.white,
    marginLeft: getFigmaDimension(4),
  },
  addVideoCard: {
    width: getFigmaDimension(160),
    height: getFigmaDimension(200),
    borderRadius: getFigmaDimension(12),
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addVideoText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginTop: getFigmaDimension(8),
  },
  menuCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: getFigmaDimension(16),
  },
  menuLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  menuText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(16),
  },
  menuDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginLeft: getFigmaDimension(54),
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    borderWidth: 2,
    borderColor: COLORS.error,
  },
  logoutText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.error,
    marginLeft: getFigmaDimension(8),
  },
  versionContainer: {
    alignItems: 'center',
    paddingVertical: getFigmaDimension(16),
  },
  versionText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textLight,
  },
});
