import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(16),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backButton: {
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: COLORS.backgroundGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
    flex: 1,
    textAlign: 'center',
    marginHorizontal: getFigmaDimension(16),
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: getFigmaDimension(20),
  },
  jobCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(20),
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  customerSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  customerImage: {
    width: getFigmaDimension(60),
    height: getFigmaDimension(60),
    borderRadius: getFigmaDimension(30),
    backgroundColor: COLORS.gray200,
    marginRight: getFigmaDimension(16),
  },
  customerInfo: {
    flex: 1,
  },
  label: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(4),
  },
  customerName: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: getFigmaDimension(16),
  },
  jobInfoRow: {
    flexDirection: 'row',
    marginBottom: getFigmaDimension(12),
  },
  jobInfoItem: {
    flex: 1,
  },
  value: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
  },
  section: {
    marginBottom: getFigmaDimension(24),
  },
  sectionLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(6),
  },
  required: {
    color: COLORS.error,
  },
  sectionHint: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(12),
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    paddingHorizontal: getFigmaDimension(20),
    height: getFigmaDimension(64),
  },
  currencySymbol: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(24),
    color: COLORS.textPrimary,
    marginRight: getFigmaDimension(8),
  },
  amountInput: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(24),
    color: COLORS.textPrimary,
    padding: 0,
  },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderRadius: getFigmaDimension(8),
    padding: getFigmaDimension(12),
    marginTop: getFigmaDimension(12),
  },
  warningText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: '#78350F',
    marginLeft: getFigmaDimension(8),
    flex: 1,
  },
  notesInputContainer: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    padding: getFigmaDimension(16),
  },
  notesInput: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    minHeight: getFigmaDimension(120),
    textAlignVertical: 'top',
  },
  characterCount: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    textAlign: 'right',
    marginTop: getFigmaDimension(6),
  },
  photosContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-6),
  },
  photoItem: {
    width: getFigmaDimension(100),
    height: getFigmaDimension(100),
    margin: getFigmaDimension(6),
    position: 'relative',
  },
  photoImage: {
    width: '100%',
    height: '100%',
    borderRadius: getFigmaDimension(12),
    backgroundColor: COLORS.gray200,
  },
  removePhotoButton: {
    position: 'absolute',
    top: getFigmaDimension(-8),
    right: getFigmaDimension(-8),
    width: getFigmaDimension(28),
    height: getFigmaDimension(28),
    borderRadius: getFigmaDimension(14),
    backgroundColor: COLORS.error,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  addPhotoButton: {
    width: getFigmaDimension(100),
    height: getFigmaDimension(100),
    margin: getFigmaDimension(6),
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addPhotoText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    marginTop: getFigmaDimension(6),
  },
  paymentConfirmSection: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(20),
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: getFigmaDimension(28),
    height: getFigmaDimension(28),
    borderRadius: getFigmaDimension(8),
    borderWidth: 2,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getFigmaDimension(12),
  },
  checkboxChecked: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  checkboxLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    flex: 1,
    lineHeight: getFigmaDimension(22),
  },
  importantBox: {
    backgroundColor: '#FEE2E2',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(20),
    borderWidth: 2,
    borderColor: COLORS.error,
  },
  importantHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  importantTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.error,
    marginLeft: getFigmaDimension(8),
  },
  importantContent: {
    paddingLeft: getFigmaDimension(32),
  },
  importantText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: '#7F1D1D',
    marginBottom: getFigmaDimension(8),
    lineHeight: getFigmaDimension(20),
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
  },
  infoText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: '#1E40AF',
    marginLeft: getFigmaDimension(12),
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
  bottomAction: {
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  requestOTPButton: {
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(16),
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  requestOTPButtonDisabled: {
    backgroundColor: COLORS.gray300,
    elevation: 0,
    shadowOpacity: 0,
  },
  requestOTPButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.white,
    marginLeft: getFigmaDimension(8),
  },
});
