import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  skipButton: {
    position: 'absolute',
    top: getFigmaDimension(60),
    right: getFigmaDimension(24),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(16),
    paddingVertical: getFigmaDimension(10),
    borderRadius: getFigmaDimension(20),
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    gap: getFigmaDimension(6),
  },
  skipText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textSecondary,
  },
  slide: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideContent: {
    alignItems: 'center',
    paddingHorizontal: getFigmaDimension(40),
  },
  iconContainer: {
    position: 'relative',
    marginBottom: getFigmaDimension(60),
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconGlowOuter: {
    position: 'absolute',
    width: getFigmaDimension(220),
    height: getFigmaDimension(220),
    borderRadius: getFigmaDimension(110),
    backgroundColor: '#3B82F6',
    opacity: 0.1,
  },
  iconGlowInner: {
    position: 'absolute',
    width: getFigmaDimension(180),
    height: getFigmaDimension(180),
    borderRadius: getFigmaDimension(90),
    backgroundColor: '#3B82F6',
    opacity: 0.15,
  },
  iconCircle: {
    width: getFigmaDimension(140),
    height: getFigmaDimension(140),
    borderRadius: getFigmaDimension(70),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
  },
  floatingParticle: {
    position: 'absolute',
    width: getFigmaDimension(12),
    height: getFigmaDimension(12),
    borderRadius: getFigmaDimension(6),
    backgroundColor: '#3B82F6',
    opacity: 0.3,
  },
  particle1: {
    top: getFigmaDimension(20),
    right: getFigmaDimension(40),
  },
  particle2: {
    bottom: getFigmaDimension(30),
    left: getFigmaDimension(30),
  },
  particle3: {
    top: getFigmaDimension(50),
    left: getFigmaDimension(50),
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(32),
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: getFigmaDimension(20),
    lineHeight: getFigmaDimension(40),
    letterSpacing: 0.5,
  },
  description: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(17),
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: getFigmaDimension(28),
    paddingHorizontal: getFigmaDimension(20),
  },
  decorativeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: getFigmaDimension(40),
    gap: getFigmaDimension(12),
  },
  decorativeLine: {
    width: getFigmaDimension(40),
    height: 2,
    backgroundColor: COLORS.border,
  },
  decorativeDot: {
    width: getFigmaDimension(10),
    height: getFigmaDimension(10),
    borderRadius: getFigmaDimension(5),
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(40),
    gap: getFigmaDimension(8),
  },
  dot: {
    height: getFigmaDimension(10),
    borderRadius: getFigmaDimension(5),
    overflow: 'hidden',
  },
  dotGradient: {
    flex: 1,
    borderRadius: getFigmaDimension(5),
  },
  bottomContainer: {
    paddingHorizontal: getFigmaDimension(24),
    paddingBottom: getFigmaDimension(40),
  },
  nextButton: {
    borderRadius: getFigmaDimension(16),
    overflow: 'hidden',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  nextButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: getFigmaDimension(18),
    gap: getFigmaDimension(12),
  },
  nextButtonText: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  getStartedButton: {
    borderRadius: getFigmaDimension(16),
    overflow: 'hidden',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  getStartedButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: getFigmaDimension(20),
    gap: getFigmaDimension(12),
  },
  getStartedButtonText: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(20),
    color: COLORS.white,
    letterSpacing: 0.5,
  },
});
