import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: getFigmaDimension(24),
  },
  iconContainer: {
    alignItems: 'center',
    marginBottom: getFigmaDimension(24),
  },
  iconCircle: {
    width: getFigmaDimension(120),
    height: getFigmaDimension(120),
    borderRadius: getFigmaDimension(60),
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#A7F3D0',
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(24),
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: getFigmaDimension(8),
  },
  subtitle: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(15),
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: getFigmaDimension(22),
    marginBottom: getFigmaDimension(24),
  },
  phoneNumber: {
    fontFamily: FONTS.semiBold,
    color: COLORS.textPrimary,
  },
  customerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(16),
  },
  customerImage: {
    width: getFigmaDimension(50),
    height: getFigmaDimension(50),
    borderRadius: getFigmaDimension(25),
    backgroundColor: COLORS.gray200,
    marginRight: getFigmaDimension(12),
  },
  customerInfo: {
    flex: 1,
  },
  customerName: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(2),
  },
  customerLabel: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
  },
  amountCard: {
    backgroundColor: '#D1FAE5',
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    alignItems: 'center',
    marginBottom: getFigmaDimension(20),
    borderWidth: 2,
    borderColor: COLORS.success,
  },
  amountLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: '#065F46',
    marginBottom: getFigmaDimension(8),
  },
  amountValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(36),
    color: COLORS.success,
    marginBottom: getFigmaDimension(4),
  },
  amountSubtext: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: '#059669',
  },
  instructionBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(24),
  },
  instructionText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: '#1E40AF',
    marginLeft: getFigmaDimension(12),
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
  otpSection: {
    marginBottom: getFigmaDimension(24),
  },
  otpLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: getFigmaDimension(16),
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: getFigmaDimension(24),
  },
  otpInput: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(56),
    borderWidth: 2,
    borderColor: COLORS.border,
    borderRadius: getFigmaDimension(12),
    backgroundColor: COLORS.white,
    textAlign: 'center',
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(24),
    color: COLORS.textPrimary,
  },
  otpInputFilled: {
    borderColor: COLORS.success,
    backgroundColor: '#F0FDF4',
  },
  resendContainer: {
    alignItems: 'center',
  },
  resendText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  resendLink: {
    fontFamily: FONTS.semiBold,
    color: COLORS.primary,
  },
  timerText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  timerHighlight: {
    fontFamily: FONTS.semiBold,
    color: COLORS.primary,
  },
  warningBox: {
    flexDirection: 'row',
    backgroundColor: '#FEF3C7',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    borderWidth: 2,
    borderColor: COLORS.warning,
  },
  warningContent: {
    marginLeft: getFigmaDimension(12),
    flex: 1,
  },
  warningTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(14),
    color: '#78350F',
    marginBottom: getFigmaDimension(8),
  },
  warningText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: '#78350F',
    lineHeight: getFigmaDimension(20),
  },
  bottomAction: {
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  verifyButton: {
    flexDirection: 'row',
    backgroundColor: COLORS.success,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(16),
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  verifyButtonDisabled: {
    backgroundColor: COLORS.gray300,
    elevation: 0,
    shadowOpacity: 0,
  },
  verifyButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.white,
    marginLeft: getFigmaDimension(8),
  },
  // Success Screen Styles
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: getFigmaDimension(32),
  },
  successIconContainer: {
    marginBottom: getFigmaDimension(32),
  },
  successTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(28),
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: getFigmaDimension(12),
  },
  successMessage: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(18),
    color: COLORS.success,
    textAlign: 'center',
    marginBottom: getFigmaDimension(32),
  },
  successDetails: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(32),
  },
  successDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  successDetailText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(12),
  },
  successButton: {
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(16),
    paddingHorizontal: getFigmaDimension(32),
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginBottom: getFigmaDimension(12),
  },
  successButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.white,
    marginRight: getFigmaDimension(8),
  },
  successSecondaryButton: {
    paddingVertical: getFigmaDimension(12),
  },
  successSecondaryText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.primary,
  },
});
