import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  section: {
    paddingHorizontal: getFigmaDimension(20),
    marginBottom: getFigmaDimension(24),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(16),
    marginTop: getFigmaDimension(8),
  },
  contactCardsContainer: {
    flexDirection: 'row',
    gap: getFigmaDimension(12),
  },
  contactCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(16),
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  contactIcon: {
    width: getFigmaDimension(60),
    height: getFigmaDimension(60),
    borderRadius: getFigmaDimension(30),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  contactLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(4),
  },
  contactValue: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(11),
    color: COLORS.textPrimary,
    textAlign: 'center',
  },
  quickActionsCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    overflow: 'hidden',
  },
  quickActionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: getFigmaDimension(16),
  },
  quickActionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  quickActionText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(16),
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginLeft: getFigmaDimension(54),
  },
  faqCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    marginBottom: getFigmaDimension(12),
    overflow: 'hidden',
  },
  faqHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: getFigmaDimension(16),
  },
  faqLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: getFigmaDimension(16),
  },
  faqIconContainer: {
    width: getFigmaDimension(36),
    height: getFigmaDimension(36),
    borderRadius: getFigmaDimension(18),
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getFigmaDimension(12),
  },
  faqQuestion: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
  faqAnswer: {
    paddingHorizontal: getFigmaDimension(16),
    paddingBottom: getFigmaDimension(16),
    paddingLeft: getFigmaDimension(64),
  },
  faqAnswerText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    lineHeight: getFigmaDimension(22),
  },
  tipsCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
  },
  tipItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: getFigmaDimension(16),
  },
  tipIconContainer: {
    marginRight: getFigmaDimension(12),
    marginTop: getFigmaDimension(2),
  },
  tipText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    lineHeight: getFigmaDimension(20),
    flex: 1,
  },
  supportHoursCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
  },
  supportHoursText: {
    marginLeft: getFigmaDimension(16),
    flex: 1,
  },
  supportHoursTitle: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.primary,
    marginBottom: getFigmaDimension(4),
  },
  supportHoursDescription: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: '#1E40AF',
    lineHeight: getFigmaDimension(20),
  },
  needHelpCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(32),
    alignItems: 'center',
  },
  needHelpTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(20),
    color: COLORS.textPrimary,
    marginTop: getFigmaDimension(16),
    marginBottom: getFigmaDimension(8),
  },
  needHelpText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: getFigmaDimension(22),
    marginBottom: getFigmaDimension(24),
  },
  contactSupportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#25D366',
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(14),
    paddingHorizontal: getFigmaDimension(32),
  },
  contactSupportText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.white,
    marginLeft: getFigmaDimension(8),
  },
});
