import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(16),
    backgroundColor: COLORS.white,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileImage: {
    width: getFigmaDimension(50),
    height: getFigmaDimension(50),
    borderRadius: getFigmaDimension(25),
    marginRight: getFigmaDimension(12),
    backgroundColor: COLORS.gray200,
  },
  greetingText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
  },
  userName: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
  },
  notificationButton: {
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: COLORS.backgroundGray,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: getFigmaDimension(6),
    right: getFigmaDimension(6),
    backgroundColor: COLORS.error,
    borderRadius: getFigmaDimension(8),
    minWidth: getFigmaDimension(16),
    height: getFigmaDimension(16),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: getFigmaDimension(4),
  },
  notificationBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(10),
    color: COLORS.white,
  },
  statsContainer: {
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(16),
  },
  statsCard: {
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(12),
  },
  statsIconContainer: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(24),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  statsLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.white,
    opacity: 0.9,
    marginBottom: getFigmaDimension(4),
  },
  statsValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(32),
    color: COLORS.white,
    marginBottom: getFigmaDimension(8),
  },
  statsChange: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: getFigmaDimension(8),
    paddingVertical: getFigmaDimension(4),
    borderRadius: getFigmaDimension(12),
    alignSelf: 'flex-start',
  },
  statsChangeText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(12),
    color: COLORS.white,
    marginLeft: getFigmaDimension(4),
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  smallStatsCard: {
    width: '48%',
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(16),
    alignItems: 'center',
  },
  smallStatsValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(28),
    marginTop: getFigmaDimension(8),
    marginBottom: getFigmaDimension(4),
  },
  smallStatsLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
  },
  section: {
    paddingHorizontal: getFigmaDimension(24),
    marginBottom: getFigmaDimension(24),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
  },
  sectionSubtitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.primary,
  },
  seeAllText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-6),
  },
  quickActionCard: {
    width: '23%',
    aspectRatio: 1,
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    margin: getFigmaDimension(6),
    padding: getFigmaDimension(12),
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  quickActionIcon: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(24),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(8),
  },
  quickActionText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(11),
    color: COLORS.textPrimary,
    textAlign: 'center',
  },
  profileCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
  },
  progressBarContainer: {
    height: getFigmaDimension(8),
    backgroundColor: COLORS.gray200,
    borderRadius: getFigmaDimension(4),
    overflow: 'hidden',
    marginBottom: getFigmaDimension(16),
  },
  progressBar: {
    height: '100%',
    backgroundColor: COLORS.primary,
  },
  profileTips: {
    marginBottom: getFigmaDimension(16),
  },
  profileTip: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  profileTipText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(12),
  },
  improveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: getFigmaDimension(12),
    borderRadius: getFigmaDimension(8),
    backgroundColor: COLORS.backgroundGray,
  },
  improveButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
    marginRight: getFigmaDimension(4),
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(12),
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  activityIconContainer: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(24),
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getFigmaDimension(12),
  },
  activityContent: {
    flex: 1,
  },
  activityTitle: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(2),
  },
  activityDescription: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(4),
  },
  activityTime: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textLight,
  },
  activityAmount: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.success,
  },
});
