import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  // Remove all header-related styles, they're now in Header component
  statsContainer: {
    padding: getFigmaDimension(20),
    gap: getFigmaDimension(12),
  },
  statsCard: {
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(4),
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  statsIconContainer: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(12),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  statsLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.white,
    opacity: 0.9,
    marginBottom: getFigmaDimension(4),
  },
  statsValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(36),
    color: COLORS.white,
    marginBottom: getFigmaDimension(8),
    letterSpacing: -1,
  },
  statsChange: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: getFigmaDimension(10),
    paddingVertical: getFigmaDimension(6),
    borderRadius: getFigmaDimension(12),
    alignSelf: 'flex-start',
  },
  statsChangeText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(12),
    color: COLORS.white,
    marginLeft: getFigmaDimension(4),
  },
  statsRow: {
    flexDirection: 'row',
    gap: getFigmaDimension(12),
  },
  smallStatsCard: {
    flex: 1,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(16),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  smallStatsValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(28),
    marginTop: getFigmaDimension(8),
    marginBottom: getFigmaDimension(4),
  },
  smallStatsLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(12),
  },
  section: {
    paddingHorizontal: getFigmaDimension(20),
    marginBottom: getFigmaDimension(24),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
  },
  sectionSubtitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.success,
  },
  seeAllText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-6),
  },
  quickActionCard: {
    width: '47%',
    margin: getFigmaDimension(6),
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(16),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  quickActionIcon: {
    width: getFigmaDimension(56),
    height: getFigmaDimension(56),
    borderRadius: getFigmaDimension(16),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  quickActionText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    textAlign: 'center',
  },
  profileCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  progressBarContainer: {
    height: getFigmaDimension(12),
    backgroundColor: COLORS.gray100,
    borderRadius: getFigmaDimension(6),
    marginBottom: getFigmaDimension(20),
    overflow: 'hidden',
    position: 'relative',
  },
  progressBarBackground: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.gray200,
  },
  progressBar: {
    height: '100%',
    borderRadius: getFigmaDimension(6),
  },
  profileTips: {
    marginBottom: getFigmaDimension(16),
    gap: getFigmaDimension(12),
  },
  profileTip: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileTipText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(12),
  },
  improveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.backgroundGray,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(12),
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  improveButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
    marginRight: getFigmaDimension(6),
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(12),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  activityIconContainer: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(12),
    backgroundColor: '#D1FAE5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getFigmaDimension(12),
  },
  activityContent: {
    flex: 1,
  },
  activityTitle: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(4),
  },
  activityDescription: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(4),
  },
  activityTime: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textLight,
  },
  activityAmount: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.success,
  },
});
