import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(16),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: getFigmaDimension(20),
  },
  photoSection: {
    alignItems: 'center',
    marginBottom: getFigmaDimension(32),
  },
  photoContainer: {
    position: 'relative',
    marginBottom: getFigmaDimension(12),
  },
  profilePhoto: {
    width: getFigmaDimension(120),
    height: getFigmaDimension(120),
    borderRadius: getFigmaDimension(60),
    backgroundColor: COLORS.gray200,
    borderWidth: 4,
    borderColor: COLORS.white,
  },
  changePhotoButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: COLORS.white,
  },
  photoHint: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
  },
  section: {
    marginBottom: getFigmaDimension(32),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(16),
  },
  inputGroup: {
    marginBottom: getFigmaDimension(20),
  },
  label: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(8),
  },
  required: {
    color: COLORS.error,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    paddingHorizontal: getFigmaDimension(16),
    height: getFigmaDimension(56),
  },
  input: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(12),
    padding: 0,
  },
  inputHint: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    marginTop: getFigmaDimension(6),
  },
  perHour: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  skillsScroll: {
    paddingVertical: getFigmaDimension(4),
  },
  skillChip: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(10),
    paddingHorizontal: getFigmaDimension(16),
    marginRight: getFigmaDimension(8),
    borderWidth: 2,
    borderColor: COLORS.border,
  },
  skillChipSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  skillChipText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
  },
  skillChipTextSelected: {
    color: COLORS.white,
  },
  experienceContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-4),
  },
  experienceChip: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(10),
    paddingHorizontal: getFigmaDimension(16),
    margin: getFigmaDimension(4),
    borderWidth: 2,
    borderColor: COLORS.border,
  },
  experienceChipSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  experienceText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textPrimary,
  },
  experienceTextSelected: {
    color: COLORS.white,
  },
  textareaContainer: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    padding: getFigmaDimension(16),
  },
  textarea: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    minHeight: getFigmaDimension(100),
    textAlignVertical: 'top',
  },
  characterCount: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    textAlign: 'right',
    marginTop: getFigmaDimension(6),
  },
  bottomAction: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    gap: getFigmaDimension(12),
  },
  cancelButton: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(14),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cancelButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
  },
  saveButton: {
    flex: 1.5,
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonDisabled: {
    backgroundColor: COLORS.gray300,
  },
  saveButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.white,
    marginLeft: getFigmaDimension(8),
  },
});
