import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  backButton: {
    position: 'absolute',
    top: getFigmaDimension(60),
    left: getFigmaDimension(24),
    width: getFigmaDimension(44),
    height: getFigmaDimension(44),
    borderRadius: getFigmaDimension(22),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  content: {
    flex: 1,
    paddingHorizontal: getFigmaDimension(24),
    paddingTop: getFigmaDimension(120),
  },
  iconSection: {
    alignItems: 'center',
    marginBottom: getFigmaDimension(40),
    position: 'relative',
  },
  circleOuter: {
    position: 'absolute',
    width: getFigmaDimension(200),
    height: getFigmaDimension(200),
    borderRadius: getFigmaDimension(100),
    backgroundColor: '#DDD6FE',
    opacity: 0.5,
  },
  circleMiddle: {
    position: 'absolute',
    width: getFigmaDimension(160),
    height: getFigmaDimension(160),
    borderRadius: getFigmaDimension(80),
    backgroundColor: '#C4B5FD',
    opacity: 0.6,
  },
  iconCircle: {
    width: getFigmaDimension(120),
    height: getFigmaDimension(120),
    borderRadius: getFigmaDimension(60),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
  },
  floatingDot: {
    position: 'absolute',
    width: getFigmaDimension(10),
    height: getFigmaDimension(10),
    borderRadius: getFigmaDimension(5),
    backgroundColor: '#8B5CF6',
    opacity: 0.4,
  },
  dot1: {
    top: getFigmaDimension(10),
    right: getFigmaDimension(30),
  },
  dot2: {
    bottom: getFigmaDimension(20),
    left: getFigmaDimension(20),
  },
  dot3: {
    top: getFigmaDimension(40),
    left: getFigmaDimension(40),
  },
  textSection: {
    marginBottom: getFigmaDimension(40),
    alignItems: 'center',
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(32),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(12),
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(16),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: getFigmaDimension(8),
  },
  phoneContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: getFigmaDimension(8),
  },
  phoneNumber: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.primary,
  },
  editButton: {
    width: getFigmaDimension(28),
    height: getFigmaDimension(28),
    borderRadius: getFigmaDimension(14),
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  otpSection: {
    marginBottom: getFigmaDimension(32),
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: getFigmaDimension(24),
    gap: getFigmaDimension(8),
  },
  otpInputWrapper: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: getFigmaDimension(16),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  otpInputWrapperFilled: {
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  otpInputGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  otpInput: {
    width: '100%',
    height: '100%',
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(28),
    color: COLORS.textPrimary,
    textAlign: 'center',
    backgroundColor: 'transparent',
  },
  otpInputFilled: {
    color: COLORS.white,
  },
  resendContainer: {
    alignItems: 'center',
  },
  resendButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(12),
    borderRadius: getFigmaDimension(20),
    gap: getFigmaDimension(8),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  resendText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.primary,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(12),
    borderRadius: getFigmaDimension(20),
    gap: getFigmaDimension(8),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  timerText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  timerHighlight: {
    fontFamily: FONTS.bold,
    color: COLORS.primary,
  },
  infoCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    gap: getFigmaDimension(16),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: getFigmaDimension(12),
  },
  infoText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
  spacer: {
    flex: 1,
  },
  verifyingContainer: {
    paddingBottom: getFigmaDimension(24),
  },
  verifyingCard: {
    borderRadius: getFigmaDimension(20),
    padding: getFigmaDimension(24),
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 10,
  },
  verifyingContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: getFigmaDimension(16),
  },
  verifyingText: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(20),
    color: COLORS.white,
  },
});
