import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: getFigmaDimension(20),
  },
  section: {
    marginBottom: getFigmaDimension(24),
  },
  sectionLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(6),
  },
  required: {
    color: COLORS.error,
  },
  sectionHint: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(12),
  },
  videoPreview: {
    width: '100%',
    height: getFigmaDimension(200),
    borderRadius: getFigmaDimension(16),
    backgroundColor: COLORS.gray200,
    overflow: 'hidden',
    position: 'relative',
    marginBottom: getFigmaDimension(12),
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
  },
  videoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeVideoButton: {
    position: 'absolute',
    top: getFigmaDimension(12),
    right: getFigmaDimension(12),
    width: getFigmaDimension(32),
    height: getFigmaDimension(32),
    borderRadius: getFigmaDimension(16),
    backgroundColor: COLORS.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoDuration: {
    position: 'absolute',
    bottom: getFigmaDimension(12),
    left: getFigmaDimension(12),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: getFigmaDimension(8),
    paddingVertical: getFigmaDimension(4),
    borderRadius: getFigmaDimension(12),
  },
  videoDurationText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(12),
    color: COLORS.white,
    marginLeft: getFigmaDimension(4),
  },
  uploadButton: {
    width: '100%',
    height: getFigmaDimension(200),
    borderRadius: getFigmaDimension(16),
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  uploadButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    marginTop: getFigmaDimension(12),
  },
  uploadButtonHint: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginTop: getFigmaDimension(4),
  },
  requirementsBox: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
  },
  requirementItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(8),
  },
  requirementText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(8),
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    paddingHorizontal: getFigmaDimension(16),
    height: getFigmaDimension(56),
  },
  input: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(12),
    padding: 0,
  },
  characterCount: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    textAlign: 'right',
    marginTop: getFigmaDimension(6),
  },
  textareaContainer: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    padding: getFigmaDimension(16),
  },
  textarea: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    minHeight: getFigmaDimension(100),
    textAlignVertical: 'top',
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-6),
  },
  categoryItem: {
    width: '23%',
    aspectRatio: 1,
    margin: getFigmaDimension(6),
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    padding: getFigmaDimension(8),
  },
  categoryItemSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
  },
  categoryText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(11),
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginTop: getFigmaDimension(6),
  },
  categoryTextSelected: {
    fontFamily: FONTS.semiBold,
    color: COLORS.white,
  },
  tagInputContainer: {
    flexDirection: 'row',
    gap: getFigmaDimension(12),
  },
  tagInput: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    paddingHorizontal: getFigmaDimension(16),
    height: getFigmaDimension(48),
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
  },
  addTagButton: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(12),
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addTagButtonDisabled: {
    backgroundColor: COLORS.gray300,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: getFigmaDimension(12),
    marginHorizontal: getFigmaDimension(-4),
  },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(8),
    paddingHorizontal: getFigmaDimension(12),
    margin: getFigmaDimension(4),
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  tagChipText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.primary,
    marginRight: getFigmaDimension(6),
  },
  tagCounter: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    marginTop: getFigmaDimension(6),
  },
  infoBox: {
    flexDirection: 'row',
    backgroundColor: '#FEF3C7',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    borderWidth: 1,
    borderColor: '#FCD34D',
  },
  infoContent: {
    marginLeft: getFigmaDimension(12),
    flex: 1,
  },
  infoTitle: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: '#78350F',
    marginBottom: getFigmaDimension(6),
  },
  infoText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: '#78350F',
    lineHeight: getFigmaDimension(20),
  },
  bottomActions: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    gap: getFigmaDimension(12),
  },
  saveDraftButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.backgroundGray,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(14),
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  saveDraftText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
    marginLeft: getFigmaDimension(6),
  },
  publishButton: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(14),
  },
  publishButtonDisabled: {
    backgroundColor: COLORS.gray300,
  },
  publishButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.white,
    marginLeft: getFigmaDimension(6),
  },
});
