import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(16),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backButton: {
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: COLORS.backgroundGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
    flex: 1,
    textAlign: 'center',
    marginHorizontal: getFigmaDimension(16),
  },
  saveButton: {
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: COLORS.backgroundGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  customerCard: {
    backgroundColor: COLORS.white,
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(12),
  },
  customerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  customerImage: {
    width: getFigmaDimension(60),
    height: getFigmaDimension(60),
    borderRadius: getFigmaDimension(30),
    backgroundColor: COLORS.gray200,
    marginRight: getFigmaDimension(12),
  },
  customerInfo: {
    flex: 1,
  },
  customerName: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(4),
  },
  customerRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  customerRating: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(6),
  },
  verifiedBadge: {
    width: getFigmaDimension(32),
    height: getFigmaDimension(32),
    borderRadius: getFigmaDimension(16),
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactButtons: {
    flexDirection: 'row',
    gap: getFigmaDimension(12),
  },
  contactButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(10),
    paddingVertical: getFigmaDimension(12),
  },
  contactButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.white,
    marginLeft: getFigmaDimension(8),
  },
  jobCard: {
    backgroundColor: COLORS.white,
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(12),
  },
  jobTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(22),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(12),
  },
  jobMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: getFigmaDimension(20),
  },
  metaText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(6),
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: getFigmaDimension(16),
  },
  jobDescription: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    lineHeight: getFigmaDimension(24),
  },
  imagesCard: {
    backgroundColor: COLORS.white,
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(12),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(12),
  },
  imagesScroll: {
    marginHorizontal: getFigmaDimension(-20),
    paddingHorizontal: getFigmaDimension(20),
  },
  jobImage: {
    width: getFigmaDimension(200),
    height: getFigmaDimension(150),
    borderRadius: getFigmaDimension(12),
    backgroundColor: COLORS.gray200,
    marginRight: getFigmaDimension(12),
  },
  detailsCard: {
    backgroundColor: COLORS.white,
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(12),
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-8),
  },
  detailItem: {
    width: '50%',
    padding: getFigmaDimension(8),
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  detailIconContainer: {
    width: getFigmaDimension(56),
    height: getFigmaDimension(56),
    borderRadius: getFigmaDimension(28),
    backgroundColor: COLORS.backgroundGray,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(8),
  },
  detailLabel: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(4),
  },
  detailValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(2),
  },
  detailSubValue: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(11),
    color: COLORS.textLight,
  },
  locationCard: {
    backgroundColor: COLORS.white,
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(12),
  },
  locationContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: getFigmaDimension(12),
  },
  locationText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(12),
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
  viewMapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.backgroundGray,
    borderRadius: getFigmaDimension(8),
    paddingVertical: getFigmaDimension(10),
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  viewMapText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
    marginLeft: getFigmaDimension(6),
  },
  requirementsCard: {
    backgroundColor: COLORS.white,
    padding: getFigmaDimension(20),
    marginBottom: getFigmaDimension(12),
  },
  requirementItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  requirementText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(12),
  },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginHorizontal: getFigmaDimension(20),
    marginBottom: getFigmaDimension(12),
  },
  warningText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: '#78350F',
    marginLeft: getFigmaDimension(12),
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
  bottomActions: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    gap: getFigmaDimension(12),
  },
  notInterestedButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.backgroundGray,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(14),
    borderWidth: 1,
    borderColor: COLORS.error,
  },
  notInterestedText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.error,
    marginLeft: getFigmaDimension(6),
  },
  sendResponseButton: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(14),
  },
  sendResponseText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.white,
    marginRight: getFigmaDimension(8),
  },
});
