import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: getFigmaDimension(24),
    paddingTop: getFigmaDimension(16),
    paddingBottom: getFigmaDimension(24),
  },
  progressContainer: {
    marginBottom: getFigmaDimension(24),
  },
  progressBar: {
    height: getFigmaDimension(6),
    backgroundColor: COLORS.gray200,
    borderRadius: getFigmaDimension(3),
    overflow: 'hidden',
    marginBottom: getFigmaDimension(8),
  },
  progressFill: {
    height: '100%',
    backgroundColor: COLORS.primary,
  },
  progressText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  header: {
    marginBottom: getFigmaDimension(32),
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(26),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(8),
  },
  subtitle: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(15),
    color: COLORS.textSecondary,
    lineHeight: getFigmaDimension(22),
  },
  photoSection: {
    alignItems: 'center',
    marginBottom: getFigmaDimension(32),
  },
  sectionLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(12),
    alignSelf: 'flex-start',
  },
  required: {
    color: COLORS.error,
  },
  photoContainer: {
    width: getFigmaDimension(120),
    height: getFigmaDimension(120),
    borderRadius: getFigmaDimension(60),
    overflow: 'hidden',
    marginBottom: getFigmaDimension(8),
  },
  profileImage: {
    width: '100%',
    height: '100%',
  },
  photoPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.gray100,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
  },
  photoPlaceholderText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    marginTop: getFigmaDimension(8),
  },
  photoEditBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: getFigmaDimension(36),
    height: getFigmaDimension(36),
    borderRadius: getFigmaDimension(18),
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: COLORS.white,
  },
  photoHint: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
  },
  inputSection: {
    marginBottom: getFigmaDimension(24),
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    paddingHorizontal: getFigmaDimension(16),
    height: getFigmaDimension(56),
  },
  input: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(12),
    padding: 0,
  },
  errorText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.error,
    marginTop: getFigmaDimension(6),
  },
  skillSection: {
    marginBottom: getFigmaDimension(32),
  },
  skillHint: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(16),
  },
  skillsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-6),
  },
  skillItem: {
    width: '30%',
    aspectRatio: 1,
    margin: getFigmaDimension(6),
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    padding: getFigmaDimension(8),
  },
  skillItemSelected: {
    borderColor: COLORS.primary,
    backgroundColor: '#EFF6FF',
  },
  skillIconContainer: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(24),
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getFigmaDimension(8),
  },
  skillIconContainerSelected: {
    backgroundColor: COLORS.primary,
  },
  skillName: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(12),
    color: COLORS.textPrimary,
    textAlign: 'center',
  },
  skillNameSelected: {
    fontFamily: FONTS.semiBold,
    color: COLORS.primary,
  },
  continueButton: {
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(16),
    paddingHorizontal: getFigmaDimension(24),
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  continueButtonDisabled: {
    backgroundColor: COLORS.gray300,
    elevation: 0,
    shadowOpacity: 0,
  },
  continueButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.white,
    marginRight: getFigmaDimension(8),
  },
});
