import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(8),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: getFigmaDimension(12),
    paddingHorizontal: getFigmaDimension(16),
    marginRight: getFigmaDimension(8),
    borderRadius: getFigmaDimension(20),
  },
  activeTab: {
    backgroundColor: COLORS.primary,
  },
  tabText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  activeTabText: {
    fontFamily: FONTS.semiBold,
    color: COLORS.white,
  },
  tabBadge: {
    backgroundColor: COLORS.error,
    borderRadius: getFigmaDimension(10),
    minWidth: getFigmaDimension(20),
    height: getFigmaDimension(20),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: getFigmaDimension(6),
    paddingHorizontal: getFigmaDimension(6),
  },
  tabBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(11),
    color: COLORS.white,
  },
  jobsList: {
    flex: 1,
  },
  jobsListContent: {
    padding: getFigmaDimension(16),
  },
  jobCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(16),
    borderWidth: 2,
    borderColor: COLORS.border,
    position: 'relative',
  },
  newJobCard: {
    borderColor: COLORS.primary,
    backgroundColor: '#FEFEFE',
  },
  newBadge: {
    position: 'absolute',
    top: getFigmaDimension(16),
    right: getFigmaDimension(16),
    backgroundColor: COLORS.error,
    paddingHorizontal: getFigmaDimension(10),
    paddingVertical: getFigmaDimension(4),
    borderRadius: getFigmaDimension(12),
  },
  newBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(11),
    color: COLORS.white,
  },
  customerSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  customerImage: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(24),
    backgroundColor: COLORS.gray200,
    marginRight: getFigmaDimension(12),
  },
  customerInfo: {
    flex: 1,
  },
  customerName: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(4),
  },
  customerRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  customerRating: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(4),
  },
  locationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    paddingHorizontal: getFigmaDimension(10),
    paddingVertical: getFigmaDimension(6),
    borderRadius: getFigmaDimension(12),
  },
  locationText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(12),
    color: COLORS.primary,
    marginLeft: getFigmaDimension(4),
  },
  jobDetails: {
    marginBottom: getFigmaDimension(12),
  },
  jobTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(17),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(6),
  },
  jobDescription: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    lineHeight: getFigmaDimension(20),
  },
  jobMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: getFigmaDimension(12),
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: getFigmaDimension(16),
    marginBottom: getFigmaDimension(8),
  },
  metaText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(6),
  },
  jobActions: {
    flexDirection: 'row',
    gap: getFigmaDimension(12),
  },
  callButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.backgroundGray,
    borderRadius: getFigmaDimension(10),
    paddingVertical: getFigmaDimension(12),
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  callButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
    marginLeft: getFigmaDimension(6),
  },
  respondButton: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(10),
    paddingVertical: getFigmaDimension(12),
  },
  respondButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.white,
    marginRight: getFigmaDimension(6),
  },
  completeButton: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.success,
    borderRadius: getFigmaDimension(10),
    paddingVertical: getFigmaDimension(12),
  },
  completeButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.white,
    marginLeft: getFigmaDimension(6),
  },
  completedBadge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D1FAE5',
    borderRadius: getFigmaDimension(10),
    paddingVertical: getFigmaDimension(12),
  },
  completedText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.success,
    marginLeft: getFigmaDimension(6),
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: getFigmaDimension(80),
  },
  emptyStateTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(20),
    color: COLORS.textPrimary,
    marginTop: getFigmaDimension(16),
    marginBottom: getFigmaDimension(8),
  },
  emptyStateText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
});
