import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(16),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backButton: {
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: COLORS.backgroundGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
    flex: 1,
    textAlign: 'center',
    marginHorizontal: getFigmaDimension(16),
  },
  shareButton: {
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: COLORS.backgroundGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  statusCard: {
    backgroundColor: COLORS.white,
    margin: getFigmaDimension(20),
    borderRadius: getFigmaDimension(20),
    padding: getFigmaDimension(32),
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statusIconContainer: {
    marginBottom: getFigmaDimension(16),
  },
  statusTitle: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(8),
  },
  amountValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(40),
    color: COLORS.success,
    marginBottom: getFigmaDimension(16),
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D1FAE5',
    paddingHorizontal: getFigmaDimension(16),
    paddingVertical: getFigmaDimension(8),
    borderRadius: getFigmaDimension(20),
  },
  statusBadgeText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(13),
    color: COLORS.success,
    marginLeft: getFigmaDimension(6),
  },
  section: {
    paddingHorizontal: getFigmaDimension(20),
    marginBottom: getFigmaDimension(24),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(12),
  },
  customerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(16),
  },
  customerImage: {
    width: getFigmaDimension(60),
    height: getFigmaDimension(60),
    borderRadius: getFigmaDimension(30),
    backgroundColor: COLORS.gray200,
    marginRight: getFigmaDimension(12),
  },
  customerInfo: {
    flex: 1,
  },
  customerName: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(4),
  },
  customerPhone: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(6),
  },
  customerLocation: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  customerLocationText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(4),
  },
  callButton: {
    width: getFigmaDimension(44),
    height: getFigmaDimension(44),
    borderRadius: getFigmaDimension(22),
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailsCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(4),
  },
  detailLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
  },
  detailValue: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    textAlign: 'right',
    flex: 1,
    marginLeft: getFigmaDimension(16),
  },
  detailDescription: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    lineHeight: getFigmaDimension(22),
    marginTop: getFigmaDimension(4),
  },
  detailDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: getFigmaDimension(16),
  },
  breakdownCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
  },
  breakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(12),
  },
  breakdownLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  breakdownValue: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
  },
  breakdownDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: getFigmaDimension(16),
  },
  breakdownTotalLabel: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
  },
  breakdownTotalValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(20),
    color: COLORS.success,
  },
  paymentMethodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D1FAE5',
    padding: getFigmaDimension(12),
    borderRadius: getFigmaDimension(8),
    marginTop: getFigmaDimension(12),
  },
  paymentMethodText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.success,
    marginLeft: getFigmaDimension(8),
  },
  transactionCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
  },
  transactionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  transactionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  transactionLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    marginLeft: getFigmaDimension(12),
  },
  transactionValue: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(13),
    color: COLORS.textPrimary,
    textAlign: 'right',
    marginLeft: getFigmaDimension(16),
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D1FAE5',
    paddingHorizontal: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(6),
    borderRadius: getFigmaDimension(12),
  },
  verifiedText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(12),
    color: COLORS.success,
    marginLeft: getFigmaDimension(4),
  },
  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  downloadButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.primary,
    marginLeft: getFigmaDimension(8),
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginHorizontal: getFigmaDimension(20),
  },
  infoText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: '#1E40AF',
    marginLeft: getFigmaDimension(12),
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
});
