import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: getFigmaDimension(24),
    paddingVertical: getFigmaDimension(16),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(24),
    color: COLORS.textPrimary,
  },
  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.backgroundGray,
    paddingHorizontal: getFigmaDimension(16),
    paddingVertical: getFigmaDimension(10),
    borderRadius: getFigmaDimension(20),
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  downloadText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
    marginLeft: getFigmaDimension(6),
  },
  scrollView: {
    flex: 1,
  },
  earningsCard: {
    margin: getFigmaDimension(20),
    borderRadius: getFigmaDimension(20),
    padding: getFigmaDimension(24),
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  earningsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  earningsLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.white,
    opacity: 0.9,
  },
  earningsMonth: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.white,
    marginTop: getFigmaDimension(4),
  },
  monthSelector: {
    width: getFigmaDimension(40),
    height: getFigmaDimension(40),
    borderRadius: getFigmaDimension(20),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  earningsValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(40),
    color: COLORS.white,
    marginBottom: getFigmaDimension(8),
  },
  earningsChange: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(6),
    borderRadius: getFigmaDimension(12),
    alignSelf: 'flex-start',
    marginBottom: getFigmaDimension(20),
  },
  earningsChangeText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.white,
    marginLeft: getFigmaDimension(6),
  },
  earningsStats: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: getFigmaDimension(20),
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.2)',
  },
  earningsStatItem: {
    flex: 1,
    alignItems: 'center',
  },
  earningsStatValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(24),
    color: COLORS.white,
    marginBottom: getFigmaDimension(4),
  },
  earningsStatLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.white,
    opacity: 0.8,
  },
  earningsStatDivider: {
    width: 1,
    height: getFigmaDimension(40),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  quickStatsContainer: {
    flexDirection: 'row',
    paddingHorizontal: getFigmaDimension(20),
    marginBottom: getFigmaDimension(20),
    gap: getFigmaDimension(12),
  },
  quickStatCard: {
    flex: 1,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    alignItems: 'center',
  },
  quickStatValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(22),
    marginTop: getFigmaDimension(12),
    marginBottom: getFigmaDimension(4),
  },
  quickStatLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
  },
  section: {
    paddingHorizontal: getFigmaDimension(20),
    marginBottom: getFigmaDimension(24),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
  },
  seeAllText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(14),
    color: COLORS.primary,
  },
  pendingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderRadius: getFigmaDimension(8),
    padding: getFigmaDimension(12),
    marginBottom: getFigmaDimension(12),
  },
  pendingInfoText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: '#78350F',
    marginLeft: getFigmaDimension(8),
    flex: 1,
  },
  transactionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(12),
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  pendingTransactionCard: {
    borderWidth: 2,
    borderColor: COLORS.warning,
  },
  transactionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  transactionIcon: {
    width: getFigmaDimension(48),
    height: getFigmaDimension(48),
    borderRadius: getFigmaDimension(24),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getFigmaDimension(12),
  },
  transactionInfo: {
    flex: 1,
  },
  transactionCustomer: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(2),
  },
  transactionJob: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(6),
  },
  transactionMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  transactionDate: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textLight,
    marginLeft: getFigmaDimension(4),
  },
  transactionTime: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textLight,
    marginLeft: getFigmaDimension(4),
  },
  transactionRight: {
    alignItems: 'flex-end',
  },
  transactionAmount: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.success,
    marginBottom: getFigmaDimension(4),
  },
  pendingAmount: {
    color: COLORS.warning,
  },
  pendingBadge: {
    backgroundColor: '#FEF3C7',
    paddingHorizontal: getFigmaDimension(8),
    paddingVertical: getFigmaDimension(4),
    borderRadius: getFigmaDimension(12),
  },
  pendingBadgeText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(11),
    color: '#78350F',
  },
  breakdownCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
  },
  breakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: getFigmaDimension(16),
  },
  breakdownLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  breakdownDot: {
    width: getFigmaDimension(12),
    height: getFigmaDimension(12),
    borderRadius: getFigmaDimension(6),
    marginRight: getFigmaDimension(12),
  },
  breakdownLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  breakdownValue: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
  },
  breakdownDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: getFigmaDimension(12),
  },
  breakdownTotalLabel: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
  },
  breakdownTotalValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(20),
    color: COLORS.primary,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginHorizontal: getFigmaDimension(20),
  },
  infoText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: '#166534',
    marginLeft: getFigmaDimension(12),
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
});
