import { StyleSheet } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundGray,
  },
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: getFigmaDimension(20),
  },
  jobSummaryCard: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(24),
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  jobSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: getFigmaDimension(8),
  },
  jobSummaryTitle: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    marginLeft: getFigmaDimension(8),
  },
  jobSummaryCustomer: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(8),
  },
  jobSummaryBudget: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  jobSummaryBudgetText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.success,
    marginLeft: getFigmaDimension(6),
  },
  section: {
    marginBottom: getFigmaDimension(24),
  },
  sectionLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(6),
  },
  required: {
    color: COLORS.error,
  },
  sectionHint: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(12),
  },
  quickRepliesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-4),
  },
  quickReplyChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(8),
    paddingHorizontal: getFigmaDimension(12),
    margin: getFigmaDimension(4),
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  quickReplyText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.primary,
    marginRight: getFigmaDimension(6),
  },
  messageInputContainer: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    padding: getFigmaDimension(16),
  },
  messageInput: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(15),
    color: COLORS.textPrimary,
    minHeight: getFigmaDimension(120),
    textAlignVertical: 'top',
  },
  characterCount: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(12),
    color: COLORS.textSecondary,
    textAlign: 'right',
    marginTop: getFigmaDimension(6),
  },
  quoteInputs: {
    flexDirection: 'row',
    gap: getFigmaDimension(12),
    marginBottom: getFigmaDimension(12),
  },
  quoteInputWrapper: {
    flex: 1,
  },
  inputLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    marginBottom: getFigmaDimension(8),
  },
  quoteInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    paddingHorizontal: getFigmaDimension(16),
    height: getFigmaDimension(56),
  },
  currencySymbol: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
    marginRight: getFigmaDimension(4),
  },
  quoteInput: {
    flex: 1,
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.textPrimary,
    padding: 0,
  },
  perDay: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#D1FAE5',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
    marginBottom: getFigmaDimension(12),
  },
  totalLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(15),
    color: '#065F46',
  },
  totalValue: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(22),
    color: COLORS.success,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: getFigmaDimension(12),
  },
  checkbox: {
    width: getFigmaDimension(24),
    height: getFigmaDimension(24),
    borderRadius: getFigmaDimension(6),
    borderWidth: 2,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: getFigmaDimension(12),
  },
  checkboxLabel: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textPrimary,
    flex: 1,
  },
  availabilityOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: getFigmaDimension(-6),
  },
  availabilityOption: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(12),
    borderWidth: 2,
    borderColor: COLORS.border,
    paddingVertical: getFigmaDimension(14),
    margin: getFigmaDimension(6),
    alignItems: 'center',
  },
  availabilityOptionSelected: {
    borderColor: COLORS.primary,
    backgroundColor: '#EFF6FF',
  },
  availabilityText: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
  },
  availabilityTextSelected: {
    fontFamily: FONTS.semiBold,
    color: COLORS.primary,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: getFigmaDimension(12),
    padding: getFigmaDimension(16),
  },
  infoText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(13),
    color: '#1E40AF',
    marginLeft: getFigmaDimension(12),
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
  bottomAction: {
    backgroundColor: COLORS.white,
    paddingHorizontal: getFigmaDimension(20),
    paddingVertical: getFigmaDimension(16),
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  sendButton: {
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    borderRadius: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(16),
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  sendButtonDisabled: {
    backgroundColor: COLORS.gray300,
    elevation: 0,
    shadowOpacity: 0,
  },
  sendButtonText: {
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(16),
    color: COLORS.white,
    marginLeft: getFigmaDimension(8),
  },
});
