import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONTS, getFigmaDimension } from '../../../utils';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  backButton: {
    position: 'absolute',
    top: getFigmaDimension(60),
    left: getFigmaDimension(24),
    width: getFigmaDimension(44),
    height: getFigmaDimension(44),
    borderRadius: getFigmaDimension(22),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  content: {
    flex: 1,
    paddingHorizontal: getFigmaDimension(24),
    paddingTop: getFigmaDimension(120),
  },
  iconSection: {
    alignItems: 'center',
    marginBottom: getFigmaDimension(40),
    position: 'relative',
  },
  circleOuter: {
    position: 'absolute',
    width: getFigmaDimension(200),
    height: getFigmaDimension(200),
    borderRadius: getFigmaDimension(100),
    backgroundColor: '#DBEAFE',
    opacity: 0.5,
  },
  circleMiddle: {
    position: 'absolute',
    width: getFigmaDimension(160),
    height: getFigmaDimension(160),
    borderRadius: getFigmaDimension(80),
    backgroundColor: '#BFDBFE',
    opacity: 0.6,
  },
  iconCircle: {
    width: getFigmaDimension(120),
    height: getFigmaDimension(120),
    borderRadius: getFigmaDimension(60),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
  },
  floatingDot: {
    position: 'absolute',
    width: getFigmaDimension(10),
    height: getFigmaDimension(10),
    borderRadius: getFigmaDimension(5),
    backgroundColor: '#3B82F6',
    opacity: 0.4,
  },
  dot1: {
    top: getFigmaDimension(10),
    right: getFigmaDimension(30),
  },
  dot2: {
    bottom: getFigmaDimension(20),
    left: getFigmaDimension(20),
  },
  dot3: {
    top: getFigmaDimension(40),
    left: getFigmaDimension(40),
  },
  textSection: {
    marginBottom: getFigmaDimension(40),
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(32),
    color: COLORS.textPrimary,
    marginBottom: getFigmaDimension(12),
    textAlign: 'center',
    lineHeight: getFigmaDimension(40),
  },
  subtitle: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(16),
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: getFigmaDimension(24),
    paddingHorizontal: getFigmaDimension(20),
  },
  inputSection: {
    marginBottom: getFigmaDimension(24),
  },
  inputCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(20),
    padding: getFigmaDimension(6),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    marginBottom: getFigmaDimension(12),
  },
  countryCodeContainer: {
    marginRight: getFigmaDimension(8),
  },
  countryCodeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: getFigmaDimension(16),
    paddingVertical: getFigmaDimension(16),
    borderRadius: getFigmaDimension(16),
    gap: getFigmaDimension(8),
  },
  countryCodeText: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.textPrimary,
  },
  phoneInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: getFigmaDimension(16),
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
  },
  phoneInput: {
    flex: 1,
    fontFamily: FONTS.semiBold,
    fontSize: getFigmaDimension(20),
    color: COLORS.textPrimary,
    padding: 0,
  },
  checkmarkContainer: {
    marginLeft: getFigmaDimension(8),
  },
  checkmark: {
    width: getFigmaDimension(28),
    height: getFigmaDimension(28),
    borderRadius: getFigmaDimension(14),
    justifyContent: 'center',
    alignItems: 'center',
  },
  characterCounter: {
    fontFamily: FONTS.medium,
    fontSize: getFigmaDimension(13),
    color: COLORS.textSecondary,
    textAlign: 'right',
    marginTop: getFigmaDimension(8),
  },
  featuresSection: {
    backgroundColor: COLORS.white,
    borderRadius: getFigmaDimension(16),
    padding: getFigmaDimension(20),
    gap: getFigmaDimension(16),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  featureIconContainer: {
    marginRight: getFigmaDimension(12),
  },
  featureText: {
    fontFamily: FONTS.regular,
    fontSize: getFigmaDimension(14),
    color: COLORS.textSecondary,
    flex: 1,
    lineHeight: getFigmaDimension(20),
  },
  spacer: {
    flex: 1,
  },
  buttonSection: {
    paddingBottom: getFigmaDimension(24),
  },
  continueButton: {
    borderRadius: getFigmaDimension(16),
    overflow: 'hidden',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  continueButtonDisabled: {
    shadowOpacity: 0,
    elevation: 0,
  },
  continueButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: getFigmaDimension(18),
    gap: getFigmaDimension(12),
  },
  continueButtonText: {
    fontFamily: FONTS.bold,
    fontSize: getFigmaDimension(18),
    color: COLORS.white,
    letterSpacing: 0.5,
  },
});
